version: '3'
services:

    es-client:
        command: -- ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 --watch index.js
        volumes: 
            - ./es-client:/usr/src/app
        ports: 
            - 9229:9229