version: '3'
services:

    es-client:
        build: ./es-client
        volumes: 
            - ./es-client:/usr/src/app
        ports: 
            - 3001:3000
            - 9229:9229
        depends_on: 
            - es
        networks: 
            - esnet

    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks: 
            - esnet

    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.0
        environment:
            ELASTICSEARCH_HOSTS: "http://es:9200"
        ports: 
            - 5601:5601
        depends_on: 
            - es
        networks: 
            - esnet

    hq:
        image: elastichq/elasticsearch-hq
        environment:
            HQ_DEFAULT_URL: "http://es:9200"
        ports: 
            - 5000:5000
        depends_on: 
            - es
        networks: 
            - esnet

volumes: 
    esdata:
        driver: local

networks: 
    esnet:
        driver: bridge